### ISSUE TITLE
git clone does not work

### ISSUE THREAD

**Issue by LeOS-GSI** [Qhojoblinks-7/personal_health_assistant#1]
I have tried to clone your repo, but git clone is asking for user name and password

**Comment by Qhojoblinks-7** [comment]
Ok. So I've tried cloning it on different command lines a it worked perfectly.

**Comment by Qhojoblinks-7** [comment]
Can u pls try using ur user name and password and then give me a feed back

**Comment by LeOS-GSI** [comment]
OK when using my username and pw I'm getting this error
```
ich@ich:/media/ich/1TB_SSD/AndroidApks/temp$ git clone https://github.com/Qhojoblinks-7/personal-health-fitness.git
Klone nach 'personal-health-fitness' …
Username for 'https://github.com': harvey186@hotmail.com 
Password for 'https://harvey186@hotmail.com@github.com': 
remote: Repository not found.
fatal: Repository »https://github.com/Qhojoblinks-7/personal-health-fitness.git/« not found.
```
That's the link in your readme and you really have no personal-health-fitness.git 


I have tried your main repo personal-health-assistant.git but then the compile command from your readme isn't working.

there is no src folder !!!

**Comment by Qhojoblinks-7** [comment]
ok i might have done something wrong
i will let u know when um done

**Comment by Qhojoblinks-7** [comment]
thanks for the reminder

**Comment by Qhojoblinks-7** [comment]
You were right the was an error in the readme file, which is the the URL

**Comment by Qhojoblinks-7** [comment]
I've correct it. Thanks once again

**Comment by Qhojoblinks-7** [comment]
You are

**Comment by LeOS-GSI** [comment]
I'm sorry, the compile command, point 2 is still not working.
there is no src folder in your health_assistant  repo And running it from root folder is failing

**Comment by LeOS-GSI** [comment]
here the terminal out put when running he compile on root/main folder

```
ich@ich:/media/ich/1TB_SSD/AndroidApks/temp/personal_health_assistant$ gcc -o health_fitness_assistant main.c fitness.c nutrition.c bmi.c -lm
main.c:5:10: fatal error: graph.h: File or Folder not found
    5 | #include "graph.h"
      |          ^~~~~~~~~
compilation terminated.
nutrition.c: In function ‘logMeal’:
nutrition.c:19:67: error: ‘struct Meal’ has no member named ‘calories’; did you mean ‘calpories’?
   19 |                 fprintf(nutritionLog, "Calories: %d, ", meal_data.calories);
      |                                                                   ^~~~~~~~
      |                                                                   calpories
nutrition.c:22:57: error: ‘meal_fats’ undeclared (first use in this function); did you mean ‘meal_data’?
   22 |                 fprintf(nutritionLog, "Fats: %.2f g\n", meal_fats);
      |                                                         ^~~~~~~~~
      |                                                         meal_data
nutrition.c:22:57: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by LeOS-GSI** [comment]
here the terminal out put when running he compile on root/main folder

```
ich@ich:/media/ich/1TB_SSD/AndroidApks/temp/personal_health_assistant$ gcc -o health_fitness_assistant main.c fitness.c nutrition.c bmi.c -lm
main.c:5:10: fatal error: graph.h: File or folder not found
    5 | #include "graph.h"
      |          ^~~~~~~~~
compilation terminated.
nutrition.c: In function ‘logMeal’:
nutrition.c:19:67: error: ‘struct Meal’ has no member named ‘calories’; did you mean ‘calpories’?
   19 |                 fprintf(nutritionLog, "Calories: %d, ", meal_data.calories);
      |                                                                   ^~~~~~~~
      |                                                                   calpories
nutrition.c:22:57: error: ‘meal_fats’ undeclared (first use in this function); did you mean ‘meal_data’?
   22 |                 fprintf(nutritionLog, "Fats: %.2f g\n", meal_fats);
      |                                                         ^~~~~~~~~
      |                                                         meal_data
nutrition.c:22:57: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by Qhojoblinks-7** [comment]
Yeah u are right. This is a new project I'm working on so I've not not compiled it yet

**Comment by Qhojoblinks-7** [comment]
I want to create all the files before I do that

**Comment by LeOS-GSI** [comment]
> Yeah u are right. This is a new project I'm working on so I've not not compiled it yet

OK, no problem. Let me know when you are done :)

**Comment by Qhojoblinks-7** [comment]
Hello Good morning. Trust you are well.
I've pushed some files and done the compilation too. You can check it out though there are undetected bugs I'm still looking for

**Comment by Qhojoblinks-7** [comment]
But you can still check it out and give me your suggestions. Thanks

**Comment by LeOS-GSI** [comment]
> But you can still check it out and give me your suggestions. Thanks

yeah, I will keep in touch with you.

**Comment by LeOS-GSI** [comment]
I'm sorry, still not working 
ich@ich:/media/ich/1TB_SSD/AndroidApks/temp/personal_health_assistant$ gcc -Wall -Wextra -std=c99 -o health_assistant main.c calculate_bmi.c classify_health_status.c create_profile.c daily_calorie_intake.c display_educational_content.c display_exercise_chart.c display_food_chart.c display_fitness_progress.c display_line_chart.c display_nutritional_habits.c exercise_recommendations.c log_exercise.c log_food.c load_logs_from_file.c save_logs_to_file.c view_exercise_logs.c view_food_logs.c welcome.c -lm -lncurses
cc1: fatal error: display_line_chart.c: Datei oder Verzeichnis nicht gefunden
compilation terminated.
cc1: fatal error: display_nutritional_habits.c: Datei oder Verzeichnis nicht gefunden
compilation terminated.
log_food.c: In function ‘log_food’:
log_food.c:24:40: error: ‘struct FoodLog’ has no member named ‘food’
   24 |         fgets(food_logs[*num_food_logs].food, MAX_NAME_LENGTH, stdin);
      |                                        ^
log_food.c:25:51: error: ‘struct FoodLog’ has no member named ‘food’
   25 |         int len = strlen(food_logs[*num_food_logs].food);
      |                                                   ^
log_food.c:26:49: error: ‘struct FoodLog’ has no member named ‘food’
   26 |         if (len > 0 && food_logs[*num_food_logs].food[len - 1] == '\n')
      |                                                 ^
log_food.c:28:42: error: ‘struct FoodLog’ has no member named ‘food’
   28 |                 food_logs[*num_food_logs].food[len - 1] = '\0';
      |                                          ^
save_logs_to_file.c: In function ‘save_logs_to_file’:
save_logs_to_file.c:40:63: error: ‘const struct FoodLog’ has no member named ‘food’
   40 |                 fprintf(saved_file, "Food: %s\n", food_logs[i].food);
      |                                                               ^
view_food_logs.c: In function ‘view_food_logs’:
view_food_logs.c:25:50: error: ‘const struct FoodLog’ has no member named ‘food’
   25 |                 printf("Food: %s\n", food_logs[i].food);
      |                                                  ^

**Comment by Qhojoblinks-7** [comment]
But it was running perfectly on my machine 🤔🤔

**Comment by Qhojoblinks-7** [comment]
Did u use the make file?

**Comment by LeOS-GSI** [comment]
> Did u use the make file?

with make I'm  getting this

ich@ich:/media/ich/1TB_SSD/AndroidApks/temp/personal_health_assistant$ make
make: There is nothing to be done for the "all" target.

**Comment by LeOS-GSI** [comment]
But anyway, I fear, that's not what I'm looking for. It's for Desktop, right ? I'm looking for a PDA for Android

**Comment by Qhojoblinks-7** [comment]
> > Did u use the make file?
> 
> with make I'm  getting this
> 
> ich@ich:/media/ich/1TB_SSD/AndroidApks/temp/personal_health_assistant$ make
> make: There is nothing to be done for the "all" target.
> 
> 

I don't really know what the problem is. Cos I just got behind my laptop and everything is running perfectly

**Comment by Qhojoblinks-7** [comment]
> But anyway, I fear, that's not what I'm looking for. It's for Desktop, right ? I'm looking for a PDA for Android

Sorry to disappoint Sir. It's just something that I'm working on to test my skills in C language. I'm just a beginner. I wish I could have given u what u want.
But I pray after completing my course I will be able to help u in anything u want

**Comment by LeOS-GSI** [comment]
> > > Did u use the make file?
> > 
> > 
> > with make I'm  getting this
> > ich@ich:/media/ich/1TB_SSD/AndroidApks/temp/personal_health_assistant$ make
> > make: There is nothing to be done for the "all" target.
> 
> I don't really know what the problem is. Cos I just got behind my laptop and everything is running perfectly

I think I have installed all needed stuff for compiling, because I'm building a lot android GSIs and apps. It's Linux Mint I'm using and Pop!OS. I'm not familiar with C and C++. But could it be that there are some path hardcoded ? I'm working on external SSD and you, I think in home folder. Could be that this will produce the errors.

**Comment by Qhojoblinks-7** [comment]
Some of the things you are mentioning, I'm not familiar with,😅😅. But I used ncurses.h for the interface and I used GNUPLOT for the graph aspects

**Comment by Qhojoblinks-7** [comment]
So maybe that might be the problem
